name: Build luci-app-xray

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "SDK_URL=https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz" >> $GITHUB_ENV
          echo "SDK_HOME=$GITHUB_WORKSPACE/openwrt-sdk" >> $GITHUB_ENV

      - name: Download and Extract SDK
        run: |
          mkdir -p "$SDK_HOME"
          wget -qO- "$SDK_URL" | tar -xJ --strip-components=1 -C "$SDK_HOME"

      - name: Prepare luci-app-xray package
        run: |
          cd "$SDK_HOME/package"
          # 把源码放到 package/luci-app-xray
          mkdir -p luci-app-xray
          cp -r $GITHUB_WORKSPACE/* luci-app-xray/
          ls -R luci-app-xray

      - name: Update and Install Feeds
        run: |
          cd "$SDK_HOME"
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build luci-app-xray
        run: |
          cd "$SDK_HOME"
          make defconfig
          make package/luci-app-xray/compile V=s -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-xray
          path: |
            ${{ env.SDK_HOME }}/bin/packages/*/*/luci-app-xray*.ipk
