- name: Download and Unzip SDK
  run: |
    cd "$CACHE_DIR_SDK"
    echo "::warning::Forcing re-download of SDK to bypass cache..."

    # 下载 sha256sums 文件
    wget -q -O sha256sums "$SDK_URL_PATH/sha256sums"
    if [ $? -ne 0 ]; then
      echo "::error::Failed to download sha256sums file from $SDK_URL_PATH."
      exit 1
    fi

    # 提取 SDK 文件名
    SDK_FILE="$(grep "$SDK_NAME" sha256sums | cut -d' ' -f2 | sed 's/*//g')"
    if [ -z "$SDK_FILE" ]; then
      echo "::error::SDK file not found in sha256sums."
      exit 1
    fi

    # 删除旧文件（强制重新下载）
    if [ -f "$SDK_FILE" ]; then
      rm -f "$SDK_FILE"
    fi

    # 下载 SDK 文件（带重试）
    MAX_RETRIES=3
    RETRY_COUNT=0
    while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
      wget -q -O "$SDK_FILE" "$SDK_URL_PATH/$SDK_FILE"
      if [ $? -eq 0 ]; then
        break
      else
        echo "::warning::Download failed. Retrying ($((RETRY_COUNT + 1))/$MAX_RETRIES)..."
        RETRY_COUNT=$((RETRY_COUNT + 1))
        sleep 5
      fi
    done

    if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
      echo "::error::Failed to download SDK file after $MAX_RETRIES attempts."
      exit 1
    fi

    # 验证文件存在性和大小
    if [ ! -f "$SDK_FILE" ]; then
      echo "::error::SDK file $SDK_FILE does not exist."
      exit 1
    fi
    SDK_SIZE=$(stat -c "%s" "$SDK_FILE")
    if [ "$SDK_SIZE" -lt 1000000 ]; then  # 假设 SDK 文件至少 1MB
      echo "::error::SDK file size is too small (only $SDK_SIZE bytes). Likely corrupted."
      exit 1
    fi

    # 手动验证校验和（调试输出）
    EXPECTED_CHECKSUM=$(grep "$SDK_FILE" sha256sums | awk '{print $1}')
    ACTUAL_CHECKSUM=$(sha256sum "$SDK_FILE" | awk '{print $1}')
    if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]; then
      echo "::error::SDK file checksum mismatch!"
      echo "Expected: $EXPECTED_CHECKSUM"
      echo "Actual:   $ACTUAL_CHECKSUM"
      exit 1
    fi

    # 创建目标目录
    mkdir -p "$SDK_HOME"

    # 解压 SDK（直接使用 tar 处理 .tar.xz）
    echo "Extracting $SDK_FILE..."
    tar -xJvf "$SDK_FILE" -C "$SDK_HOME" --strip=1
    if [ $? -ne 0 ]; then
      echo "::error::Failed to extract SDK file $SDK_FILE."
      exit 1
    fi

    cd -
